# Generated by Django 5.0.7 on 2024-07-17 16:48

import bookings.services
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WashingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.PositiveSmallIntegerField(help_text='enter per minute')),
                ('number_of_places', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_days', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('arrival_time', models.TimeField()),
                ('full_name', models.CharField(max_length=75)),
                ('phone_number', models.CharField(max_length=13, validators=[bookings.services.phone_number_validate])),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('washing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.washingtype')),
            ],
        ),
    ]
